### ISSUE TITLE
Duplication of header writing

### ISSUE THREAD

**Issue by DipandaAser** [Sanix-Darker/aliash#4]
In most of your handler you are setting the content type manually like this 👇
https://github.com/Sanix-Darker/aliash/blob/17de501a59fa570d192320d0fa5868d9c5f213b4/backend/handlers.go#L32

But this is not necesserally since that *gin.Context.JSON() function set it for you under the hood. So when you use it like this : 
https://github.com/Sanix-Darker/aliash/blob/17de501a59fa570d192320d0fa5868d9c5f213b4/backend/handlers.go#L33

under the hood gin does this: 
![image](https://user-images.githubusercontent.com/54457328/185159262-53313ce9-8c26-4dc3-8f4a-36e212a7b4d7.png)

https://github.com/gin-gonic/gin/blob/1c48977cca9e7a0a41c763376b6921a23cd06fe2/render/json.go#L70

**Comment by Sanix-Darker** [comment]
Closing this since the related PR got merged !
